sudo: false
language: node_js
matrix:
  include:
    - os: linux
      dist: xenial
      sudo: false
      node_js: "6"
    - os: linux
      dist: xenial
      sudo: false
      node_js: "8"
    - os: linux
      dist: xenial
      sudo: false
      node_js: "10"
    - os: osx
      osx_image: xcode10.2
      node_js: "6"
    - os: osx
      osx_image: xcode10.2
      node_js: "8"
    - os: osx
      osx_image: xcode10.2
      node_js: "10"
script:
  - npm run test
after_success:
  - npm run report-coverage
